services:
  web:
    image: nginx:alpine
    container_name: my-compose-frontend
    ports:
      - "80:80"        # 🔥 Sirf Nginx public internet ke liye open rahega!
    env_file:
      - .env
    networks:
      - app-net
    volumes:
      - ./templates:/tmp/templates
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend-api
    command: >
      sh -c "envsubst < /tmp/templates/index.html.template > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"

  backend-api:
    image: node:20-alpine
    container_name: my-compose-backend
    working_dir: /app
    # 🔒 PORTS MAPPING REMOVED — Ab ye sirf internal network par baat karega
    volumes:
      - ./server:/app
    networks:
      - app-net
    depends_on:
      database:
        condition: service_healthy
    command: node index.js

  database:
    image: mongo:4.4
    container_name: my-compose-database
    networks:
      - app-net
    volumes:
      - db-data:/data/db
    # 🔒 PORTS MAPPING REMOVED — Database completely secure from outside world
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

networks:
  app-net:
    driver: bridge

volumes:
  db-data:
    driver: local
