services:
  web:
    image: nginx
    container_name: my-compose-frontend
    ports:
      - "80:80"
    env_file:
      - .env
    networks:
      - app-net
    volumes:
      - ./templates:/tmp/templates
    command: >
      bash -c "envsubst < /tmp/templates/index.html.template > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"

  backend-api:
    image: alpine
    container_name: my-compose-backend
    networks:
      - app-net
    command: sleep 3600

networks:
  app-net:
    driver: bridge
