services:
  web-server:
    image: nginx:alpine
    container_name: web-server
    ports:
      - "8085:80"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
